DirectoryPath: "build"
CheckExternal: false
EnforceHTTPS: true
CheckSelfReferencesAsInternal: true
CheckInternalHash: true
BaseURL: https://circleci.com/docs
IgnoreAltEmpty: true
IgnoreInternalEmptyHash: true
IgnoreURLs:
  - "\\[url\\]"  # Escaped literal [url] placeholder in search templates
  - "^/docs/_/"  # UI assets from 404 page (uses absolute paths)
  - "^/docs/$"   # Root docs links from 404 page
IgnoreDirs:
  - "api"
OutputDir: ".htmltest"
