DirectoryPath: "build"
CheckExternal: false
EnforceHTTPS: true
CheckSelfReferencesAsInternal: true
CheckInternalHash: true
BaseURL: https://circleci.com/docs
IgnoreAltEmpty: true
IgnoreInternalEmptyHash: true
IgnoreURLs:
  - "[url]"
  - "/docs/_/.*"  # Ignore all UI assets from 404 page (uses absolute paths)
  - "/docs/$"     # Ignore root docs links from 404 page
IgnoreDirs:
  - "api"
OutputDir: ".htmltest"
