site:
  title: CircleCI Documentation
  url: https://circleci.com/docs
  robots: allow
content:
  sources:
  - url: .
    start_path: docs/root
  - url: .
    start_path: docs/guides
  - url: .
    start_path: docs/reference
  - url: .
    start_path: docs/server-admin
    branches: [HEAD, server-v*]
  - url: .
    start_path: docs/contributors
ui:
  bundle:
    url: ./ui-bundle.zip
output:
  dir: ./build
  clean: true
  destinations:
  - provider: fs
