site:
  title: CircleCI Documentation
  url: https://circleci.com/docs
  robots: allow
content:
  sources:
  - url: .
    start_paths:
    - docs/root
    - docs/guides
    - docs/reference
    - docs/orbs
    - docs/server-admin
    - docs/contributors
ui:
  bundle:
    url: ./ui-bundle.zip
output:
  dir: ./build
  clean: true
  destinations:
  - provider: fs
